title: Saumya Saxena
logo: /assets/img/saumyasaxena_cropped.jpeg
#description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
cv_url: https://drive.google.com/file/d/14sy7RQlhJdVefQQ1ae-rS51pHvTnA51Q/view
is_user_page: true
# Site Author
author:
  links:
    - label: "saumyas@andrew.cmu.edu"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/saxena_saumya"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/saumyasaxena/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SaumyaSaxena"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   # url: "https://instagram.com/"